export const USER_LOADING = 'USER_LOADING'
export const USER_EXPIRED = 'USER_EXPIRED'
export const USER_FOUND = 'USER_FOUND'
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SILENT_RENEW_ERROR = 'SILENT_RENEW_ERROR'
export const SESSION_TERMINATED = 'SESSION_TERMINATED'

export const RECEIVE_ERROR = 'RECEIVE_ERROR'
export const RECEIVE_UPLOAD_ERROR = 'RECEIVE_UPLOAD_ERROR'
export const REFRESH_STATE = 'REFRESH_STATE'
export const SUPPRESS_EDITS = 'SUPPRESS_EDITS'

export const RECEIVE_AUTH_USER = 'RECEIVE_AUTH_USER'
export const REDIRECTING = 'REDIRECTING'
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR'

export const REQUEST_INSTITUTIONS = 'REQUEST_INSTITUTIONS'
export const RECEIVE_INSTITUTIONS = 'RECEIVE_INSTITUTIONS'

export const REQUEST_INSTITUTION = 'REQUEST_INSTITUTION'
export const RECEIVE_INSTITUTION = 'RECEIVE_INSTITUTION'

export const SHOULD_FETCH_INSTITUTIONS = 'SHOULD_FETCH_INSTITUTIONS'
export const CLEAR_INSTITUTIONS = 'CLEAR_INSTITUTIONS'

export const UPDATE_FILING_PERIOD = 'UPDATE_FILING_PERIOD'
export const UPDATE_PATHNAME = 'UPDATE_PATHNAME'
export const SET_LEI = 'SET_LEI'

export const START_REFILE = 'START_REFILE'
export const REFILE_READY = 'REFILE_READY'

export const REQUEST_VERIFY_QUALITY = 'REQUEST_VERIFY_QUALITY'
export const REQUEST_VERIFY_MACRO = 'REQUEST_VERIFY_MACRO'
export const VERIFY_QUALITY = 'VERIFY_QUALITY'
export const VERIFY_MACRO = 'VERIFY_MACRO'

export const SHOW_CONFIRM = 'SHOW_CONFIRM'
export const HIDE_CONFIRM = 'HIDE_CONFIRM'
export const PICK_SORT = 'PICK_SORT'
export const REQUEST_CSV = 'REQUEST_CSV'

export const SELECT_FILE = 'SELECT_FILE'
export const SELECT_NEW_FILE = 'SELECT_NEW_FILE'
export const SET_FILENAME = 'SET_FILENAME'
export const RECEIVE_FILE_ERRORS = 'RECEIVE_FILE_ERRORS'
export const REQUEST_UPLOAD = 'REQUEST_UPLOAD'
export const RECEIVE_UPLOAD = 'RECEIVE_UPLOAD'

export const REQUEST_FILING = 'REQUEST_FILING'
export const RECEIVE_FILING = 'RECEIVE_FILING'

export const PAGINATION_FADE_IN = 'PAGINATION_FADE_IN'
export const PAGINATION_FADE_OUT = 'PAGINATION_FADE_OUT'

export const REQUEST_SUBMISSION = 'REQUEST_SUBMISSION'
export const RECEIVE_SUBMISSION = 'RECEIVE_SUBMISSION'

export const REQUEST_EDITS = 'REQUEST_EDITS'
export const RECEIVE_EDITS = 'RECEIVE_EDITS'

export const REQUEST_EDIT_TYPE = 'REQUEST_EDIT_TYPE'
export const RECEIVE_EDIT_TYPE = 'RECEIVE_EDIT_TYPE'

export const REQUEST_EDIT = 'REQUEST_EDIT'
export const RECEIVE_EDIT = 'RECEIVE_EDIT'

export const REQUEST_SUMMARY = 'REQUEST_SUMMARY'
export const RECEIVE_SUMMARY = 'RECEIVE_SUMMARY'

export const REQUEST_PARSE_ERRORS = 'REQUEST_PARSE_ERRORS'
export const RECEIVE_PARSE_ERRORS = 'RECEIVE_PARSE_ERRORS'

export const REQUEST_SIGNATURE = 'REQUEST_SIGNATURE'
export const RECEIVE_SIGNATURE = 'RECEIVE_SIGNATURE'
export const REQUEST_SIGNATURE_POST = 'REQUEST_SIGNATURE_POST'
export const RECEIVE_SIGNATURE_POST = 'RECEIVE_SIGNATURE_POST'
export const POST_SIGNATURE = 'POST_SIGNATURE'
export const CHECK_SIGNATURE = 'CHECK_SIGNATURE'

export const UPDATE_STATUS = 'UPDATE_STATUS'

export const REQUEST_LATEST_SUBMISSION = 'REQUEST_LATEST_SUBMISSION'
export const RECEIVE_LATEST_SUBMISSION = 'RECEIVE_LATEST_SUBMISSION'

export const RECEIVE_INSTITUTION_NOT_FOUND = 'RECEIVE_INSTITUTION_NOT_FOUND'

export const RECEIVE_FILING_PAGE = 'RECEIVE_FILING_PAGE'
