export default [
  { id: '-1', name: 'None chosen' },
  { id: '1', name: 'National Bank' },
  { id: '2', name: 'State Member Bank' },
  { id: '3', name: 'State Non-Member Bank' },
  { id: '4', name: 'State Chartered Thrift' },
  { id: '5', name: 'Federal Chartered Thrift' },
  { id: '6', name: 'Credit Unions' },
  { id: '7', name: 'Federal Branch or Agency of FBO' },
  { id: '8', name: 'Branch or Agency of FB' },
  { id: '9', name: 'MBS of National Bank' },
  { id: '10', name: 'MBS of State Member Bank' },
  { id: '11', name: 'MBS of State Non-Member Bank' },
  { id: '12', name: 'MBS of BHC' },
  { id: '13', name: 'MBS of CU' },
  { id: '14', name: 'Independent MBS' },
  { id: '15', name: 'MBS of S&L HC' },
  { id: '16', name: 'MBS of State-Chartered Thrift' },
  { id: '17', name: 'MBS of Federal-Chartered Thrift' },
  { id: '18', name: 'Affiliate' },
]
