apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmda-frontend.fullname" . }}
  labels:
    app: {{ include "hmda-frontend.name" . }}
    chart: {{ include "hmda-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hmda-frontend.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels: 
    service: {{ include "hmda-frontend.fullname" . }}-mapping
  name: {{ include "hmda-frontend.fullname" . }}-mapping
spec:
  {{- if .Values.ambassador_id }}
  ambassador_id: {{ .Values.ambassador_id }}
  {{- end}}
  {{- if .Values.ambassador_host }}
  host: {{ .Values.ambassador_host }}
  {{- end}}
  prefix: /
  rewrite: /
  service: {{ include "hmda-frontend.fullname" . }}:{{ .Values.service.port }}
