apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmda-frontend.fullname" . }}
  labels:
    app: {{ include "hmda-frontend.name" . }}
    chart: {{ include "hmda-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "hmda-frontend.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  labels: 
    service: {{ include "hmda-frontend.fullname" . }}-ambassador
  name: {{ include "hmda-frontend.fullname" . }}-ambassador
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: hmda_frontend_mapping
      ambassador_id: ambassador-default-1
      prefix: /
      rewrite: /
      service: {{ include "hmda-frontend.fullname" . }}:{{ .Values.service.port }}
spec:
  clusterIP: None
