// /hmda-platform/common/src/main/scala/hmda/model/filing/lar/LoanApplicationRegister.scala

// Data Field Name | Data Field Type | Valid Values | Descriptions and Examples | Data Point Name
const LAR_SCHEMA_RAW = `
"Record Identifier"| lar.larIdentifier.id.toString | 1 - TS, 2 - LAR| | |
"Legal Entity Identifier (LEI)"| lar.larIdentifier.LEI | 10BX939C5543TQA1144M | | Legal Entity Identifier (LEI)
"Universal Loan Identifier (ULI) or Non-Universal Loan Identifier (NULI)"  | lar.loan.ULI | ULI Example - 10BX939C5543TQA1144M999143X38, NULI Example - 999143X | Universal Loan Identifier (ULI) or Non-Universal Loan Identifier (NULI)
"Application Date" | lar.loan.applicationDate | 20210721 (or) NA | Application Date
"Loan Type"        | lar.loan.loanType.code.toString | 1 - Conventional (not insured or guaranteed by FHA{comma} VA{comma} RHS{comma} or FSA), 2 - Federal Housing Administration insured (FHA), 3 - Veterans Affairs guaranteed (VA) , 4 - USDA Rural Housing Service or Farm Service Agency guaranteed (RHS or FSA),  | Loan Type
"Loan Purpose"     | lar.loan.loanPurpose.code.toString | 1 - Home purchase, 2 - Home improvement, 31 - Refinancing, 32 - Cash-out refinancing , 4 - Other purpose, 5 - Not applicable, | Loan Purpose
"Preapproval"      | lar.action.preapproval.code.toString | 1 - Preapproval requested, 2 - Preapproval not requested, | |
"Construction Method"| lar.loan.constructionMethod.code.toString | 1 - Site{hyphen}built, 2 - Manufactured Home, | |
"Occupancy Type"   | lar.loan.occupancy.code.toString | 1 - Principal residence, 2 - Second residence, 3 - Investment property, | |
"Loan Amount"      | lar.loan.amount.toString | 110500 (or) 110500.00 | |
"Action Taken"     | lar.action.actionTakenType.code.toString | 1 - Loan originated, 2 - Application approved but not accepted, 3 - Application denied, 4 - Application withdrawn by applicant, 5 - File closed for incompleteness, 6 - Purchased loan, 7 - Preapproval request denied, 8 - Preapproval request approved but not accepted, | |
"Action Taken Date"| lar.action.actionTakenDate.toString | 20210721 | |
"Street Address"   | lar.geography.street | 456 W Somewhere Ave Apt 201 (or) NA (or) Exempt | Property Address
"City"   | lar.geography.city | Anytown (or) NA (or) Exempt |  Property Address
"State"  | lar.geography.state | CA (or) NA | Property Location & Property Address
"Zip Code"         | lar.geography.zipCode | 90049{hyphen}9998 (or) NA (or) Exempt | Property Address
"County" | lar.geography.county | 06037 (or) NA | Property Location
"Census Tract"     | lar.geography.tract | 06037264000 (or) NA | Property Location
"Ethnicity of Applicant or Borrower: 1"      | lar.applicant.ethnicity.ethnicity1.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Applicant or Borrower: 2"      | lar.applicant.ethnicity.ethnicity2.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Applicant or Borrower: 3"      | lar.applicant.ethnicity.ethnicity3.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Applicant or Borrower: 4"      | lar.applicant.ethnicity.ethnicity4.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Applicant or Borrower: 5"      | lar.applicant.ethnicity.ethnicity5.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Applicant or Borrower: Free Form Text Field for Other Hispanic or Latino"        | lar.applicant.ethnicity.otherHispanicOrLatino | Specify in text the Applicant’s or Borrower’s Other Hispanic or Latino ethnicity(ies) provided by the Applicant or Borrower. Otherwise{comma} leave this data field blank. | Ethnicity | MAX_100 
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: 1"| lar.coApplicant.ethnicity.ethnicity1.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: 2"| lar.coApplicant.ethnicity.ethnicity2.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: 3"| lar.coApplicant.ethnicity.ethnicity3.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: 4"| lar.coApplicant.ethnicity.ethnicity4.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: 5"| lar.coApplicant.ethnicity.ethnicity5.code.toString | 1 - Hispanic or Latino, 11 - Mexican, 12 - Puerto Rican, 13 - Cuban, 14 - Other Hispanic or Latino , 2 - Not Hispanic or Latino , 3 - Information not provided by applicant in mail{comma} internet{comma} or telephone application , 4 - Not applicable,  | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower: Free Form Text Field for Other Hispanic or Latino"  | lar.coApplicant.ethnicity.otherHispanicOrLatino | Specify in text the Applicant’s or Borrower’s Other Hispanic or Latino ethnicity(ies) provided by the Applicant or Borrower. Otherwise{comma} leave this data field blank. | Ethnicity | MAX_100 
"Ethnicity of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"   | lar.applicant.ethnicity.ethnicityObserved.code.toString | 1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname , 3 - Not applicable, | Ethnicity
"Ethnicity of Co{hyphen}Applicant or Co{hyphen}Borrower Collected on the Basis of Visual Observation or Surname"       | lar.coApplicant.ethnicity.ethnicityObserved.code.toString | 1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname , 3 - Not applicable, 4 - No co{hyphen}applicant, | Ethnicity
"Race of Applicant or Borrower: 1" | lar.applicant.race.race1.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White, 6 - Information not provided by applicant in mail{comma} internet{comma} or telephone application, 7 - Not applicable, | Race
"Race of Applicant or Borrower: 2" | lar.applicant.race.race2.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White| Race
"Race of Applicant or Borrower: 3" | lar.applicant.race.race3.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White| Race
"Race of Applicant or Borrower: 4" | lar.applicant.race.race4.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White| Race
"Race of Applicant or Borrower: 5" | lar.applicant.race.race5.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White| Race
"Race of Applicant or Borrower: Free Form Text Field for American Indian or Alaska Native Enrolled or Principal Tribe"       | lar.applicant.race.otherNativeRace | Specify in text the Applicant’s or Borrower’s American Indian or Alaska Native Enrolled or Principal Tribe if Race provided by the Applicant or Borrower. Otherwise{comma} leave this data field blank. | Race | MAX_100 
"Race of Applicant or Borrower: Free Form Text Field for Other Asian"      | lar.applicant.race.otherAsianRace | Specify in text the Applicant’s or Borrower’s Other Asian race(s) provided by the Applicant or Borrower. Otherwise{comma} leave this data field blank.  |Race | MAX_100 
"Race of Applicant or Borrower: Free Form Text Field for Other Pacific Islander"     | lar.applicant.race.otherPacificIslanderRace | Specify in text the Applicant’s or Borrower’s Other Pacific Islander race(s) provided by the Applicant or Borrower. Otherwise{comma} leave this data field blank. | Race | MAX_100 
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: 1"     | lar.coApplicant.race.race1.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White, 6 - Information not provided by applicant in mail{comma} internet{comma} or telephone application, 7 - Not applicable, 8 - No co{hyphen}applicant | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: 2"     | lar.coApplicant.race.race2.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: 3"     | lar.coApplicant.race.race3.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: 4"     | lar.coApplicant.race.race4.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: 5"     | lar.coApplicant.race.race5.code.toString | 1 - American Indian or Alaska Native, 2 - Asian, 21 - Asian Indian , 22 - Chinese, 23 - Filipino, 24 - Japanese , 25 - Korean, 26 - Vietnamese, 27 - Other Asian, 3 - Black or African American Native Hawaiian or Other Pacific Islander, 4 - Native Hawaiian or Other Pacific Islander, 41 - Native Hawaiian, 42 - Guamanian or Chamorro, 43 - Samoan, 44 - Other Pacific Islander Race, 5 - White | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: Free Form Text Field for American Indian or Alaska Native Enrolled or Principal Tribe" | lar.coApplicant.race.otherNativeRace | Specify in text the Co{hyphen}Applicant’s or Co{hyphen}Borrower’s American Indian or Alask a Native Enrolled or Principal Tribe if provided by the Co{hyphen}Applicant or Co{hyphen}Borrower. Otherwise{comma} leave this data field blank. | Race | MAX_100 
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: Free Form Text Field for Other Asian"| lar.coApplicant.race.otherAsianRace | Specify in text the Co{hyphen}Applicant’s or Co{hyphen}Borrower’s Other Asian race(s) provided by the Co{hyphen}Applicant or Co{hyphen}Borrower. Otherwise{comma} leave this data field blank. | Race | MAX_100 
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower: Free Form Text Field for Other Pacific Islander"         | lar.coApplicant.race.otherPacificIslanderRace | Specify in text the Co{hyphen}Applicant’s or Co{hyphen}Borrower’s Other Pacific Islander race(s) provided by the Co{hyphen}Applicant or Co{hyphen}Borrower. Otherwise{comma} leave this data field blank. | Race | MAX_100 
"Race of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"        | lar.applicant.race.raceObserved.code.toString | 1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname , 3 - Not applicable, | Race
"Race of Co{hyphen}Applicant or Co{hyphen}Borrower Collected on the Basis of Visual Observation or Surname"  | lar.coApplicant.race.raceObserved.code.toString | 1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname , 3 - Not applicable, 4 - No co{hyphen}applicant, | Ethnicity
"Sex of Applicant or Borrower" | lar.applicant.sex.sexEnum.code.toString | 1 - Male, 2 - Female, 3 - Information not provided by applicant in mail{comma} internet{comma} or Sex 4 telephone application, 4 - Not applicable, 6 - Applicant selected both male and female, | Sex
"Sex of Co{hyphen}Applicant or Co{hyphen}Borrower"         | lar.coApplicant.sex.sexEnum.code.toString | 1 - Male, 2 - Female, 3 - Information not provided by applicant in mail{comma} internet{comma} or Sex 4 telephone application, 4 - Not applicable, 6 - Applicant selected both male and female, | Sex
"Sex of Applicant or Borrower Collected on the Basis of Visual Observation or Surname"         | lar.applicant.sex.sexObservedEnum.code.toString | 1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname, 3 - Not applicable | Sex
"Sex of Co{hyphen}Applicant or Co{hyphen}Borrower Collected on the Basis of Visual Observation or Surname"   | lar.coApplicant.sex.sexObservedEnum.code.toString |1 - Collected on the basis of visual observation or surname, 2 - Not collected on the basis of visual observation or surname, 3 - Not applicable, 4 - No co{hyphen}applicant, | Sex
"Age of Applicant or Borrower" | lar.applicant.age.toString | Numeric-24, 8888 - NA | Sex
"Age of Co{hyphen}Applicant or Co{hyphen}Borrower"         | lar.coApplicant.age.toString | Numeric-24, 8888 - NA, 9999 - No co{hyphen}applicant | Age
"Income" | lar.income | 36 (or) -36 (or) NA | |
"Type of Purchaser"| lar.purchaserType.code.toString |0 - Not applicable, 1 - Fannie Mae, 2 - Ginnie Mae, 3 - Freddie Mac, 4 - Farmer Mac, 5 - Private securitizer, 6 - Commercial bank{comma} savings bank{comma} or savings association, 71 - Credit union{comma} mortgage company{comma} or finance company, 72 - Life insurance company, 8 - Affiliate institution, 9 - Other type of purchaser, | |
"Rate Spread"      | lar.loan.rateSpread | 0.428 (or) {hyphen}0.428 (or) NA (or) Exempt | |
"HOEPA Status"     | lar.hoepaStatus.code.toString | 1 - High-cost mortgage, 2 - Not a high-cost mortgage , 3 - Not applicable, | |
"Lien Status"      | lar.lienStatus.code.toString | 1 -  Secured by a first lien, 2 - Secured by a subordinate lien | |
"Credit Score of Applicant or Borrower"      | lar.applicant.creditScore.toString | Numeric-650, 7777 - Credit score is not a number, 8888 - Not applicable, 1111 - Exempt | Credit Score
"Credit Score of Co{hyphen}Applicant or Co{hyphen}Borrower"| lar.coApplicant.creditScore.toString | Numeric-650, 7777 - Credit score is not a number, 8888 - Not applicable, 9999 - No co{hyphen}applicant, 1111 - Exempt | Credit Score
"Applicant or Borrower, Name and Version of Credit Scoring Model"| lar.applicant.creditScoreType.code.toString | 1 - Equifax Beacon 5.0, 2 - Experian Fair Isaac Risk Model v2 3 , 3 - TransUnion FICO Risk Score Classic 04, 4 - TransUnion FICO Risk Score Classic 98, 5 - VantageScore 2.0, 6 - VantageScore 3.0, 7 - More than one credit scoring model, 8 - Other credit scoring model, 9 - Not applicable , 1111 - Exempt, | Credit Score
"Applicant or Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8"     | lar.applicant.otherCreditScoreModel | Specify in text the applicant’s or borrower’s Other credit scoring model if 8 is entered. Otherwise{comma} leave this data field blank. | Credit Score | MAX_100 
"Co{hyphen}Applicant or Co{hyphen}Borrower, Name and Version of Credit Scoring Model"    | lar.coApplicant.creditScoreType.code.toString | 1 - Equifax Beacon 5.0, 2 - Experian Fair Isaac Risk Model v2 3 , 3 - TransUnion FICO Risk Score Classic 04, 4 - TransUnion FICO Risk Score Classic 98, 5 - VantageScore 2.0, 6 - VantageScore 3.0, 7 - More than one credit scoring model, 8 - Other credit scoring model, 9 - Not applicable , 10 - No co{hyphen}applicant, 1111 - Exempt, | Credit Score
"Co{hyphen}Applicant or Co{hyphen}Borrower, Name and Version of Credit Scoring Model: Conditional Free Form Text Field for Code 8"         | lar.coApplicant.otherCreditScoreModel | Specify in text the co{hyphen}applicant’s or coborrower’s Other credit scoring model if 8 is entered. Otherwise{comma} leave this data field blank. | Credit Score | MAX_100 
"Reason for Denial: 1"         | lar.denial.denialReason1.code.toString | 1 - Debt{hyphen}to{hyphen}income ratio, 2 - Employment history, 3 - Credit history, 4 - Collateral, 5 - Insufficient cash (downpayment{comma} closing costs), 6 - Unverifiable information , 7 - Credit application incomplete , 8 - Mortgage insurance denied, 9 - Other, 10 - Not applicable, 1111 - Exempt, | Reason for Denial
"Reason for Denial: 2"         | lar.denial.denialReason2.code.toString | 1 - Debt{hyphen}to{hyphen}income ratio, 2 - Employment history, 3 - Credit history, 4 - Collateral, 5 - Insufficient cash (downpayment{comma} closing costs), 6 - Unverifiable information , 7 - Credit application incomplete , 8 - Mortgage insurance denied, 9 - Other | Reason for Denial
"Reason for Denial: 3"         | lar.denial.denialReason3.code.toString | 1 - Debt{hyphen}to{hyphen}income ratio, 2 - Employment history, 3 - Credit history, 4 - Collateral, 5 - Insufficient cash (downpayment{comma} closing costs), 6 - Unverifiable information , 7 - Credit application incomplete , 8 - Mortgage insurance denied, 9 - Other | Reason for Denial
"Reason for Denial: 4"         | lar.denial.denialReason4.code.toString | 1 - Debt{hyphen}to{hyphen}income ratio, 2 - Employment history, 3 - Credit history, 4 - Collateral, 5 - Insufficient cash (downpayment{comma} closing costs), 6 - Unverifiable information , 7 - Credit application incomplete , 8 - Mortgage insurance denied, 9 - Other | Reason for Denial
"Reason for Denial: Conditional Free Form Text Field for Code 9" | lar.denial.otherDenialReason | Specify in text the Other Denial Reason(s) if Code 9 is entered. Otherwise{comma} leave this data field blank. | Reason for Denial | MAX_255 
"Total Loan Costs" | lar.loanDisclosure.totalLoanCosts | 2399.04 (or) NA (or) Exempt | Total Loan Costs or Total Points and Fees
"Total Points and Fees"        | lar.loanDisclosure.totalPointsAndFees | 2399.04 (or) NA (or) Exempt | Total Loan Costs or Total Points and Fees
"Origination Charges"| lar.loanDisclosure.originationCharges |2399.04 (or) NA (or) Exempt | Origination Charges
"Discount Points"  | lar.loanDisclosure.discountPoints |2399.04 (or) NA (or) Exempt | Discount Points
"Lender Credits"   | lar.loanDisclosure.lenderCredits | 1500.24 (or) NA (or) Exempt | |
"Interest Rate"    | lar.loan.interestRate | 4.125 (or) NA (or) Exempt | 
"Prepayment Penalty Term"      | lar.loan.prepaymentPenaltyTerm | 24 (or) NA (or) Exempt |
"Debt-to-Income Ratio"         | lar.loan.debtToIncomeRatio | 42.95 (or) -42.95 (or) NA (or) Exempt |
"Combined Loan-to-Value Ratio" | lar.loan.combinedLoanToValueRatio | 80.05 (or) NA (or) Exempt  |
"Loan Term"        | lar.loan.loanTerm | 360 (or) NA (or) Exempt | 
"Introductory Rate Period"     | lar.loan.introductoryRatePeriod | 24 (or) NA (or) Exempt |
"Balloon Payment"  | lar.nonAmortizingFeatures.balloonPayment.code.toString | 1 - Balloon payment, 2 - No balloon payment , 1111 - Exempt, |  Non{hyphen}Amortizing Features
"Interest-Only Payments"       | lar.nonAmortizingFeatures.interestOnlyPayments.code.toString |1 - Interest{hyphen}only payments, 2 - No interest{hyphen}only payments , 1111 - Exempt, | Non{hyphen}Amortizing Features
"Negative Amortization"        | lar.nonAmortizingFeatures.negativeAmortization.code.toString |1 - Negative amortization, 2 - No negative amortization , 1111 - Exempt, | Non{hyphen}Amortizing Features
"Other Non-amortizing Features"| lar.nonAmortizingFeatures.otherNonAmortizingFeatures.code.toString | 1 - Other non{hyphen}fully amortizing features , 2 - No other non{hyphen}fully amortizing features , 1111 - Exempt, |  Non{hyphen}Amortizing Features
"Property Value"   | lar.property.propertyValue | 350500 (or) NA (or) Exempt | 
"Manufactured Home Secured Property Type"    | lar.property.manufacturedHomeSecuredProperty.code.toString | 1 - Manufactured home and land, 2 - Manufactured home and not land , 3 - Not applicable, 1111 - Exempt, | 
"Manufactured Home Land Property Interest"   | lar.property.manufacturedHomeLandPropertyInterest.code.toString | 1 - Direct ownership, 2 - Indirect ownership, 3 - Paid leasehold, 4 - Unpaid leasehold, 5 - Not applicable , 1111 - Exempt, | 
"Total Units"      | lar.property.totalUnits.toString | 5 | 
"Multifamily Affordable Units" | lar.property.multiFamilyAffordableUnits | 5 (or) NA (or) Exempt |
"Submission of Application"    | lar.applicationSubmission.code.toString | 1 - Submitted directly to your institution, 2 - Not submitted directly to your institution, 3 - Not applicable, 1111 - Exempt, | Application Channel
"Initially Payable to Your Institution"      | lar.payableToInstitution.code.toString | 1 - Initially payable to your institution, 2 -  Not initially payable to your institution, 3 - Not applicable, 1111 - Exempt | Application Channel
"NMLSR ID"         | lar.larIdentifier.NMLSRIdentifier | 123450 (or) NA (or) Exempt | Mortgage Loan Originator NMLSR Identifier
"Automated Underwriting System: 1" | lar.AUS.aus1.code.toString | 1 -  Desktop Underwriter (DU), 2 -  Loan Prospector (LP) or Loan Product Advisor, 3 -  Technology Open to Approved Lenders (TOTAL) Scorecard, 4 -  Guaranteed Underwriting System 6 (GUS), 5 -  Other, 6 -  Not applicable, 7 -  Internal Proprietary System, 1111 -  Exempt, | Automated Underwriting System
"Automated Underwriting System: 2" | lar.AUS.aus2.code.toString | 1 -  Desktop Underwriter (DU), 2 -  Loan Prospector (LP) or Loan Product Advisor, 3 -  Technology Open to Approved Lenders (TOTAL) Scorecard, 4 -  Guaranteed Underwriting System 6 (GUS), 5 -  Other, 7 -  Internal Proprietary System | Automated Underwriting System
"Automated Underwriting System: 3" | lar.AUS.aus3.code.toString | 1 -  Desktop Underwriter (DU), 2 -  Loan Prospector (LP) or Loan Product Advisor, 3 -  Technology Open to Approved Lenders (TOTAL) Scorecard, 4 -  Guaranteed Underwriting System 6 (GUS), 5 -  Other, 7 -  Internal Proprietary System | Automated Underwriting System
"Automated Underwriting System: 4" | lar.AUS.aus4.code.toString | 1 -  Desktop Underwriter (DU), 2 -  Loan Prospector (LP) or Loan Product Advisor, 3 -  Technology Open to Approved Lenders (TOTAL) Scorecard, 4 -  Guaranteed Underwriting System 6 (GUS), 5 -  Other, 7 -  Internal Proprietary System | Automated Underwriting System
"Automated Underwriting System: 5" | lar.AUS.aus5.code.toString | 1 -  Desktop Underwriter (DU), 2 -  Loan Prospector (LP) or Loan Product Advisor, 3 -  Technology Open to Approved Lenders (TOTAL) Scorecard, 4 -  Guaranteed Underwriting System 6 (GUS), 5 -  Other, 7 -  Internal Proprietary System | Automated Underwriting System
"Automated Underwriting System: Conditional Free Form Text Field for Code 5"         | lar.AUS.otherAUS | Specify in text the Other Automated Underwriting System(s) if 5 is entered. Otherwise{comma} leave this data field blank. | Automated Underwriting System | MAX_255 
"Automated Underwriting System Result: 1"    | lar.ausResult.ausResult1.code.toString | 1 -  Approve/Eligible, 2 -  Approve/Ineligible , 3 -  Refer/Eligible, 4 -  Refer/Ineligible, 5 -  Refer with Caution , 6 -  Out of Scope, 7 -  Error, 8 -  Accept, 9 -  Caution , 10 -  Ineligible, 11 -  Incomplete, 12 -  Invalid, 13 -  Refer, 14 -  Eligible, 15 -  Unable to Determine or Unknown, 16 -  Other, 17 -  Not Applicable, 18 -  Accept/Eligible, 19 -  Accept/Ineligible, 20 -  Accept/Unable to Determine, 21 -  Refer with Caution/Eligible, 22 -  Refer with Caution/Ineligible, 23 -  Refer/Unable to Determine, 24 -  Refer with Caution/Unable to Determine, 1111 -  Exempt, |  Automated Underwriting System
"Automated Underwriting System Result: 2"    | lar.ausResult.ausResult2.code.toString | 1 -  Approve/Eligible, 2 -  Approve/Ineligible , 3 -  Refer/Eligible, 4 -  Refer/Ineligible, 5 -  Refer with Caution , 6 -  Out of Scope, 7 -  Error, 8 -  Accept, 9 -  Caution , 10 -  Ineligible, 11 -  Incomplete, 12 -  Invalid, 13 -  Refer, 14 -  Eligible, 15 -  Unable to Determine or Unknown, 16 -  Other, 17 -  Not Applicable, 18 -  Accept/Eligible, 19 -  Accept/Ineligible, 20 -  Accept/Unable to Determine, 21 -  Refer with Caution/Eligible, 22 -  Refer with Caution/Ineligible, 23 -  Refer/Unable to Determine, 24 - Refer with Caution/Unable to Determine|  Automated Underwriting System
"Automated Underwriting System Result: 3"    | lar.ausResult.ausResult3.code.toString | 1 -  Approve/Eligible, 2 -  Approve/Ineligible , 3 -  Refer/Eligible, 4 -  Refer/Ineligible, 5 -  Refer with Caution , 6 -  Out of Scope, 7 -  Error, 8 -  Accept, 9 -  Caution , 10 -  Ineligible, 11 -  Incomplete, 12 -  Invalid, 13 -  Refer, 14 -  Eligible, 15 -  Unable to Determine or Unknown, 16 -  Other, 17 -  Not Applicable, 18 -  Accept/Eligible, 19 -  Accept/Ineligible, 20 -  Accept/Unable to Determine, 21 -  Refer with Caution/Eligible, 22 -  Refer with Caution/Ineligible, 23 -  Refer/Unable to Determine, 24 - Refer with Caution/Unable to Determine|  Automated Underwriting System
"Automated Underwriting System Result: 4"    | lar.ausResult.ausResult4.code.toString | 1 -  Approve/Eligible, 2 -  Approve/Ineligible , 3 -  Refer/Eligible, 4 -  Refer/Ineligible, 5 -  Refer with Caution , 6 -  Out of Scope, 7 -  Error, 8 -  Accept, 9 -  Caution , 10 -  Ineligible, 11 -  Incomplete, 12 -  Invalid, 13 -  Refer, 14 -  Eligible, 15 -  Unable to Determine or Unknown, 16 -  Other, 17 -  Not Applicable, 18 -  Accept/Eligible, 19 -  Accept/Ineligible, 20 -  Accept/Unable to Determine, 21 -  Refer with Caution/Eligible, 22 -  Refer with Caution/Ineligible, 23 -  Refer/Unable to Determine, 24 - Refer with Caution/Unable to Determine|  Automated Underwriting System
"Automated Underwriting System Result: 5"    | lar.ausResult.ausResult5.code.toString | 1 -  Approve/Eligible, 2 -  Approve/Ineligible , 3 -  Refer/Eligible, 4 -  Refer/Ineligible, 5 -  Refer with Caution , 6 -  Out of Scope, 7 -  Error, 8 -  Accept, 9 -  Caution , 10 -  Ineligible, 11 -  Incomplete, 12 -  Invalid, 13 -  Refer, 14 -  Eligible, 15 -  Unable to Determine or Unknown, 16 -  Other, 17 -  Not Applicable, 18 -  Accept/Eligible, 19 -  Accept/Ineligible, 20 -  Accept/Unable to Determine, 21 -  Refer with Caution/Eligible, 22 -  Refer with Caution/Ineligible, 23 -  Refer/Unable to Determine, 24 - Refer with Caution/Unable to Determine|  Automated Underwriting System
"Automated Underwriting System Result: Conditional Free Form Text Field for Code 16" | lar.ausResult.otherAusResult | Specify in text the Other Automated Underwriting System Result(s) if 16 is entered. Otherwise{comma} leave this data field blank. | Automated Underwriting System | MAX_255 
"Reverse Mortgage" | lar.reverseMortgage.code.toString | 1 - Reverse mortgage ,  2 - Not a reverse mortgage, 1111 - Exempt, | 
"Open-End Line of Credit"      | lar.lineOfCredit.code.toString | 1 - Open{hyphen}end line of credit, 2 - Not an open{hyphen}end line of credit, 1111 - Exempt, | 
"Business or Commercial Purpose"   | lar.businessOrCommercialPurpose.code.toString | 1 - Primarily for a business or commercial purpose, 2 - Not primarily for a business or commercial purpose , 1111 - Exempt, |
`
exports.default = LAR_SCHEMA_RAW